# -*- coding: utf-8 -*-
"""DT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18TrvrVcmGAKB5Q48biY9zuUvMBUgdxo5

**Importar data_pokemon.csv, x.csv e y.csv**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold, GridSearchCV
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, ConfusionMatrixDisplay

x = pd.read_csv("/content/x.csv")
print("Formato do dataset:", x.shape)
x.head()

y = pd.read_csv("/content/y.csv")
print("Formato do dataset:", y.shape)
y.head()

X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.3, stratify=y, random_state=123456
)

print("Treino:", X_train.shape, " Teste:", X_test.shape)
y_train.value_counts(normalize=True)

"""# Aplicando TargetEncoder"""

from sklearn.preprocessing import TargetEncoder
encoder = TargetEncoder(smooth="auto", cv=5, random_state=123456)

X_train_scaled = encoder.fit_transform(X_train, y_train)
X_test_scaled = encoder.transform(X_test)

"""# Verificando acurácia e melhores parametros"""

from sklearn.model_selection import StratifiedKFold, GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Configuração da validação cruzada estratificada
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=123456)

# Modelo base
dt = DecisionTreeClassifier(random_state=123456)

# Espaço de busca
param_grid = {
    "max_depth": range(1, 16),
    "min_samples_leaf": [1, 5, 10],
    "ccp_alpha": [0.0, 0.01, 0.05],
    "criterion": ["entropy", "gini"]
}

# GridSearchCV com estratificação
grid = GridSearchCV(
    estimator=dt,
    param_grid=param_grid,
    cv=cv,               # aqui está a estratificação
    scoring="accuracy",
    n_jobs=-1
)

grid.fit(X_train_scaled, y_train)

print("Melhores parâmetros:", grid.best_params_)
print("Melhor acurácia (validação cruzada):", grid.best_score_)
print("Acurácia no teste:", accuracy_score(y_test, grid.best_estimator_.predict(X_test_scaled)))

"""os hiperparâmetros do DT são:
- max_depth: controla a profundidade da árvore
- min_samples_leaf: número mínimo de amostras em cada folha
- ccp_alpha: poda de complexidade
- critério: medida de impureza, a função de entropia que ele tinha falado em sala

Foi feito um grid search, para evitar o teste manual de combinação de hiperparâmetros, e essas configurações são avaliadas nos múltiplos folds, esses que por sua fez foram estratificados. Com o random_state e o cv definidos, garantimos sua reprodutibilidade, junto com a automatização do processo.
"""

dt_range_k = DecisionTreeClassifier(random_state=123456, **grid.best_params_)

# Espaço de busca
param_grid = {
    "max_depth": range(1, 16),
    "min_samples_leaf": [1, 5, 10],
    "ccp_alpha": [0.0, 0.01, 0.05],
    "criterion": ["entropy", "gini"]
}

resultados_folds = {}

for k in range(5,11):
  cv = StratifiedKFold(n_splits=k, shuffle=True, random_state=123456)
  grid = GridSearchCV(
        estimator=dt,
        param_grid=param_grid,
        cv=cv,
        scoring="accuracy",
        n_jobs=-1
    )

  grid.fit(X_train_scaled, y_train)

  resultados_folds[k] = {
        "best_params": grid.best_params_,
        "best_score": grid.best_score_,
        "test_acc": accuracy_score(y_test, grid.best_estimator_.predict(X_test_scaled))
    }
  print(f"{k} folds -> melhor={grid.best_params_}, "
          f"acc_cv={grid.best_score_:.8f}, "
          f"acc_teste={resultados_folds[k]['test_acc']:.8f}")

df_resultados = pd.DataFrame.from_dict(resultados_folds, orient="index")
print(df_resultados)

plt.figure(figsize=(8,6))
plt.plot(df_resultados.index, df_resultados["best_score"], marker="o", label="Validação (CV)")
plt.plot(df_resultados.index, df_resultados["test_acc"], marker="s", label="Teste")
plt.xlabel("Número de folds (StratifiedKFold)")
plt.ylabel("Acurácia")
plt.title("Impacto do número de folds no GridSearchCV")
plt.legend()
plt.show()

"""# Treinando o modelo final e avaliando no conjunto de teste"""

arvore = DecisionTreeClassifier(
    max_depth = grid.best_params_["max_depth"],
    min_samples_leaf = grid.best_params_["min_samples_leaf"],
    ccp_alpha = grid.best_params_["ccp_alpha"],
    criterion = grid.best_params_["criterion"],
    random_state = 123456
)

arvore.fit(X_train_scaled, y_train)

y_pred = arvore.predict(X_test_scaled)

print("Acurácia no teste:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

ConfusionMatrixDisplay.from_predictions(y_test, y_pred)
plt.title("Matriz de confusão - DT")
plt.show()
#

plt.figure(figsize=(16,8))
plot_tree(
    arvore,
    feature_names=x.columns,
    class_names=[str(c) for c in arvore.classes_],
    filled=True,
    rounded=True,
    impurity=False,
    fontsize=10
)
plt.title("Árvore de decisão treinada")
plt.show()

"""# Verificando a importância das variáveis na árvore de decisão"""

importancia = arvore.feature_importances_
feat_importancia = pd.DataFrame({
    "feature": x.columns,
    "importancia": importancia
}).sort_values(by="importancia", ascending=False)

plt.figure(figsize=(10, 25))
plt.barh(feat_importancia["feature"], feat_importancia["importancia"])
plt.xlabel("Importância")
plt.ylabel("Variável")
plt.title("Importância das variáveis - Árvore de Decisão")
plt.gca().invert_yaxis()  # deixa a mais importante no topo
plt.show()

"""# Curva ROC"""

from sklearn.metrics import roc_curve, roc_auc_score, RocCurveDisplay
import matplotlib.pyplot as plt;

y_pred_prob = arvore.predict_proba(X_test_scaled)[:, 1]
fpr_arvore, tpr_arvore, _ = roc_curve(y_test, y_pred_prob)
auc_arvore = roc_auc_score(y_test, y_pred_prob)
plt.figure(figsize=(10, 7))
plt.show()
plt.plot(
    fpr_arvore, tpr_arvore,
    label=f"DT (AUC = {auc_arvore:.3f})"
)
plt.xlabel("FPR")
plt.ylabel("TPR")
plt.title("Curva ROC")
plt.legend()
plt.grid()
plt.show()