# -*- coding: utf-8 -*-
"""KNN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XJ8Lq0pyN6uRr2ZjOUfz8NoSQpK8EHBj

**OBS: Importar dataset pré-processado**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, ConfusionMatrixDisplay


data_pokemon = pd.read_csv("/content/data_pokemon.csv")
print("Formato do dataset:", data_pokemon.shape)
data_pokemon.head()

data_pokemon.info()

"""# Separando atributos (X) e classe alvo (Y)"""

x = data_pokemon.drop(columns=["isLegendary"])
y = data_pokemon["isLegendary"]

x.info()

y.info()

"""## Exportando variáveis (x) e classe alvo (y) separadamente para .csv"""

x.to_csv("x.csv", index=False)
y.to_csv("y.csv", index=False)

"""# Divisão treino/teste"""

X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.3, stratify=y, random_state=123456
)

print("Treino:", X_train.shape, " Teste:", X_test.shape)
y_train.value_counts(normalize=True)

"""# Aplicando TargetEncoder"""

from sklearn.preprocessing import TargetEncoder
#manter o mesmo random_state da validação cruzada, se não a cada vez que rodar ele gera um k diferente
encoder = TargetEncoder(smooth="auto", cv=5, random_state=123456)

X_train_scaled = encoder.fit_transform(X_train, y_train)
X_test_scaled = encoder.transform(X_test)

print(X_train_scaled)

"""# Escolhendo o valor de k por validação cruzada"""

valores_k = range(1, 31)
acuracias_cv = []

cv_estratificado = StratifiedKFold(n_splits=5, shuffle=True, random_state=123456)

for k in valores_k:
    modelo = KNeighborsClassifier(n_neighbors=k)
    scores = cross_val_score(modelo, X_train_scaled, y_train, cv=cv_estratificado)
    acuracias_cv.append(scores.mean())

melhor_k = valores_k[int(np.argmax(acuracias_cv))]
print(f"Melhor k encontrado: {melhor_k} (acurácia média de validação cruzada: {max(acuracias_cv):.3f})")

plt.figure(figsize=(8, 4))
plt.plot(list(valores_k), acuracias_cv, marker="o")
plt.axvline(melhor_k, color="red", linestyle="--", label=f"melhor k = {melhor_k}")
plt.xlabel("k")
plt.ylabel("Acurácia média")
plt.title("Escolha de k para o KNN")
plt.legend()
plt.show()

"""# Treinando o modelo final e avaliando no conjunto de teste"""

knn_final = KNeighborsClassifier(n_neighbors=melhor_k)
knn_final.fit(X_train_scaled, y_train)

y_pred = knn_final.predict(X_test_scaled)

print(f"Acurácia no conjunto de teste: {accuracy_score(y_test, y_pred):.3f}\n")
print(classification_report(y_test, y_pred))

ConfusionMatrixDisplay.from_predictions(y_test, y_pred)
plt.title("Matriz de confusão - KNN")
plt.show()

"""# Prevendo pokemons lendários

"""

data_pokemon = data_pokemon.drop(columns=["isLegendary"])
data_pokemon_scaled = encoder.transform(data_pokemon)

previsoes = knn_final.predict(data_pokemon_scaled)

resultado = data_pokemon.copy()
resultado["isLegendary_prevista"] = previsoes

resultado.head(10)

"""# Curva ROC"""

from sklearn.metrics import roc_curve, roc_auc_score, RocCurveDisplay
import matplotlib.pyplot as plt;

y_pred_prob = knn_final.predict_proba(X_test_scaled)[:, 1]
fpr_knn, tpr_knn, _ = roc_curve(y_test, y_pred_prob)
auc_knn = roc_auc_score(y_test, y_pred_prob)
plt.figure(figsize=(10, 7))
plt.show()
plt.plot(
    fpr_knn, tpr_knn,
    label=f"KNN (AUC = {auc_knn:.3f})"
)
plt.xlabel("FPR")
plt.ylabel("TPR")
plt.title("Curva ROC")
plt.legend()
plt.grid()
plt.show()