# -*- coding: utf-8 -*-
"""NB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E9UlNkF_fpFDKbXRKyA0pjwQ-MOMNBXW

**Importar data_pokemon.csv, x.csv e y.csv**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, ConfusionMatrixDisplay

x = pd.read_csv("/content/x.csv")
print("Formato do dataset:", x.shape)
x.head()

y = pd.read_csv("/content/y.csv")
print("Formato do dataset:", y.shape)
y.head()

"""# Separando em teste e treino"""

y = y.values.ravel()   # transforma em vetor 1D

X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.3, stratify=y, random_state=123456
)

print("Treino:", X_train.shape, " Teste:", X_test.shape)

# Agora y_train é um array 1D, se quiser usar value_counts:
y_train = pd.Series(y_train)
print(y_train.value_counts(normalize=True))

"""# Aplicando TargetEncoder"""

from sklearn.preprocessing import TargetEncoder
encoder = TargetEncoder(smooth="auto", cv=5, random_state=123456)

X_train_scaled = encoder.fit_transform(X_train, y_train)
X_test_scaled = encoder.transform(X_test)

"""# Verificando qtde de folds ideal com base na acurácia"""

suavizacao_val = np.logspace(-12, 0, 25)
resultados = []

for k in range(5,11):
    cv = StratifiedKFold(n_splits=k, shuffle=True, random_state=123456)
    accu_cv = []

    for suavizacao in suavizacao_val:
        bayes = GaussianNB(var_smoothing=suavizacao)
        scores = cross_val_score(bayes, X_train_scaled, y_train, cv=cv)
        accu_cv.append(scores.mean())
        resultados.append({
            "k": k,
            "suavizacao": suavizacao,
            "acuracia": scores.mean()
        })
    df_resultados = pd.DataFrame(resultados)

    # Melhor suavização para este k
    melhor_idx = np.argmax(accu_cv)
    melhor_suav = suavizacao_val[melhor_idx]

    print(f"{k} folds -> melhor suavização={melhor_suav}, "
          f"acurácia média={accu_cv[melhor_idx]:.4f}")

    # Gráfico para este k
    plt.figure(figsize=(10,5))
    plt.plot(suavizacao_val, accu_cv, marker="o")
    plt.axvline(x=melhor_suav, color="red", linestyle="--", label=f"melhor: {melhor_suav}")
    plt.xscale("log")
    plt.legend()
    plt.title(f"Acurácia média por suavização ({k} folds)")
    plt.xlabel("Suavização")
    plt.ylabel("Acurácia")
    plt.show()

melhores = df_resultados.loc[df_resultados.groupby("k")["acuracia"].idxmax()]
print(melhores)

"""# Treinando o modelo final e avaliando no conjunto de teste"""

nb = GaussianNB(var_smoothing=melhores.suavizacao.values[1])
nb.fit(X_train_scaled, y_train)
y_pred = nb.predict(X_test_scaled)

print(f"Acurácia no conjunto de teste: {accuracy_score(y_test, y_pred)}\n")
print(classification_report(y_test, y_pred))

ConfusionMatrixDisplay.from_predictions(y_test, y_pred)
plt.title("Matriz de confusão - Naive Bayes")
plt.show()

"""# Curva ROC"""

from sklearn.metrics import roc_curve, roc_auc_score, RocCurveDisplay
import matplotlib.pyplot as plt;

y_pred_prob = nb.predict_proba(X_test_scaled)[:, 1]
fpr_nb, tpr_nb, _ = roc_curve(y_test, y_pred_prob)
auc_nb = roc_auc_score(y_test, y_pred_prob)
plt.figure(figsize=(10, 7))
plt.show()
plt.plot(
    fpr_nb, tpr_nb,
    label=f"NB (AUC = {auc_nb:.3f})"
)
plt.xlabel("FPR")
plt.ylabel("TPR")
plt.title("Curva ROC")
plt.legend()
plt.grid()
plt.show()