# -*- coding: utf-8 -*-
"""PRE-PROCESSAMENTO

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bZihsxK-Lc1AvfUXZXr-8jvO4EQVI6Lf
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.cbook import boxplot_stats
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

from google.colab import drive, files

"""# Importar dataset (https://www.kaggle.com/datasets/alopez247/pokemon)"""

import pandas as pd

data_pokemon = pd.read_csv("/content/pokemon_alopez247.csv")
data_pokemon.head()

"""# Vizualização geral

"""

data_pokemon.shape

data_pokemon.info()

"""# Substituindo valores NULL encontrados"""

#preencher Type_2
data_pokemon.fillna({"Type_2": "vazio"}, inplace=True)

"""# Retirando colunas não relevantes para a classe alvo"""

data_pokemon = data_pokemon.drop(["Number", "Egg_Group_2", "Pr_Male", "Total", "Name"], axis=1)
data_pokemon.info()

"""# Transformando features booleanas em int




"""

data_pokemon["hasGender"] = data_pokemon["hasGender"].astype(int)
data_pokemon["hasMegaEvolution"] = data_pokemon["hasMegaEvolution"].astype(int)
data_pokemon["isLegendary"] = data_pokemon["isLegendary"].astype(int)

"""# Verificando proporção dos dados na classe alvo"""

pokemons_isLegendary = data_pokemon['isLegendary'].value_counts()
print(pokemons_isLegendary)

data_pokemon.info()

#separando features numéricas e categóricas
numericos = data_pokemon.select_dtypes(include= ["int64", "float64"]).columns
categoricos = data_pokemon.select_dtypes(include=["object", "bool"]).columns

"""# Correlação entre as features numéricas e a classe alvo"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

matriz_corr = data_pokemon[numericos].corr()

plt.figure(figsize=(10, 6))
sns.heatmap(matriz_corr, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Matriz de Correlação")
plt.show()

"""# Distribuição das features numéricas"""

#plotando
data_pokemon[numericos].hist(figsize=(10,10))
plt.tight_layout()
plt.show()

"""# Verificando relação entre as features categóricas e a classe alvo"""

data_pokemon["Type_1"].unique()

data_pokemon["Type_1"].nunique()

data_pokemon["Type_2"].unique()

data_pokemon["Type_2"].nunique()

data_pokemon["Body_Style"].unique()

data_pokemon["Body_Style"].nunique()

# guia cruzada entre Type_1 e isLegendary
pd.crosstab(index=data_pokemon['Type_1'], columns=data_pokemon['isLegendary'])

# guia cruzada entre Body_Style e isLegendary
pd.crosstab(index=data_pokemon['Body_Style'], columns=data_pokemon['isLegendary'])

# guia cruzada entre Type_2 e isLegendary
pd.crosstab(index=data_pokemon['Type_2'], columns=data_pokemon['isLegendary'])

# guia cruzada entre Color e isLegendary
pd.crosstab(index=data_pokemon['Color'], columns=data_pokemon['isLegendary'])

# guia cruzada entre Egg_Group_1 e isLegendary
pd.crosstab(index=data_pokemon['Egg_Group_1'], columns=data_pokemon['isLegendary'])

data_pokemon.info()

pd.crosstab(index=data_pokemon['Egg_Group_1'], columns=data_pokemon['isLegendary'])

pd.crosstab(index=data_pokemon['Color'], columns=data_pokemon['isLegendary'])

"""# Criando coluna de pokemons com undiscovered eggs"""

data_pokemon['undiscovered_egg'] = data_pokemon['Egg_Group_1'].apply(lambda x: 1 if x == 'Undiscovered' else 0)
data_pokemon['undiscovered_egg'].value_counts()

"""# Plotando variaveis categóricas"""

for col in categoricos:
  data_pokemon[col].value_counts().plot(kind="bar")
  plt.title(f"Distribuição {col}")
  plt.show()

"""# Exportado dataset pré-processado em .csv"""

data_pokemon.to_csv("data_pokemon.csv", index=False)

data_pokemon.info()

"""# Referências

- Dataset original: https://www.kaggle.com/datasets/alopez247/pokemon
- https://cursos.alura.com.br/forum/topico-definicao-da-profundidade-da-arvore-549007
- https://scikit-learn.org/stable/modules/naive_bayes.html
- https://docs.kanaries.net/pt/topics/Scikit-Learn/sklearn-random-forest
- https://medium.com/@giselemeliobr/pok%C3%A9mon-explorando-os-dados-para-definir-lend%C3%A1rios-915dd94f5e2c
- https://rpubs.com/Beezrit/1103528
- https://seungulyu.com/pokemon_type_pca.html#Pokemon-Type-Principal-Component-Analysis
- https://www.datacamp.com/pt/tutorial/categorical-data
"""