# -*- coding: utf-8 -*-
"""RF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zkbIR7hlzLkXLLHEPjuiGVQpeCakFsXE

**Importar data_pokemon.csv, x.csv e y.csv**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import plot_tree
from sklearn.metrics import accuracy_score, classification_report, ConfusionMatrixDisplay

x = pd.read_csv("/content/x.csv")
print("Formato do dataset:", x.shape)
x.head()

y = pd.read_csv("/content/y.csv")
print("Formato do dataset:", y.shape)
y.value_counts()

"""# Seaparando em teste e treino"""

X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.3, stratify=y, random_state=123456
)

print("Treino:", X_train.shape, " Teste:", X_test.shape)
y_train.value_counts(normalize=True)

"""# Aplicando TargetEncoder"""

from sklearn.preprocessing import TargetEncoder
encoder = TargetEncoder(smooth="auto", cv=5, random_state=123456)

X_train_scaled = encoder.fit_transform(X_train, y_train)
X_test_scaled = encoder.transform(X_test)

"""# Testando hiperparâmetros"""

rf_range_k = RandomForestClassifier(random_state=123456)
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=123456)

param_grid = {
    "n_estimators": [100, 200],  #n de árvores
    "max_depth": [None, 5, 10, 15],      #prof max
    "min_samples_split": [2, 5],  #min de amostras p dividir
    "min_samples_leaf": [1, 2, 5],       #min de amostras numa folha
    "criterion": ["entropy", "gini"]     #impureza
}

grid = GridSearchCV(
        estimator=rf_range_k,
        param_grid=param_grid,
        cv=cv,
        scoring="accuracy",
        n_jobs=-1
    )

grid.fit(X_train_scaled, y_train)

print("Melhores parâmetros:", grid.best_params_)
print("Melhor acurácia (validação cruzada):", grid.best_score_)
print("Acurácia no teste:", accuracy_score(y_test, grid.best_estimator_.predict(X_test_scaled)))

"""# Avaliando relação entre qtde de folds e resultado"""

rf_range_k = RandomForestClassifier(random_state=123456)

# Espaço de busca
param_grid = {
    "n_estimators": [100, 200],  #n de árvores
    "max_depth": [None, 5, 10, 15],      #prof max
    "min_samples_split": [2, 5],  #min de amostras p dividir
    "min_samples_leaf": [1, 2, 5],       #min de amostras numa folha
    "criterion": ["entropy", "gini"]     #impureza
}

resultados_folds = {}

for k in range(5,11):
  cv = StratifiedKFold(n_splits=k, shuffle=True, random_state=123456)
  grid = GridSearchCV(
        estimator=rf_range_k,
        param_grid=param_grid,
        cv=cv,
        scoring="accuracy",
        n_jobs=-1
    )

  grid.fit(X_train_scaled, y_train)

  resultados_folds[k] = {
        "best_params": grid.best_params_,
        "best_score": grid.best_score_,
        "test_acc": accuracy_score(y_test, grid.best_estimator_.predict(X_test_scaled))
    }
  print(f"{k} folds -> melhor={grid.best_params_}, "
          f"acc_cv={grid.best_score_:.8f}, "
          f"acc_teste={resultados_folds[k]['test_acc']:.8f}")

"""# GridSearchCV para folds"""

df_resultados = pd.DataFrame.from_dict(resultados_folds, orient="index")
print(df_resultados)

plt.figure(figsize=(8,6))
plt.plot(df_resultados.index, df_resultados["best_score"], marker="o", label="Validação (CV)")
plt.plot(df_resultados.index, df_resultados["test_acc"], marker="s", label="Teste")
plt.xlabel("Número de folds (StratifiedKFold)")
plt.ylabel("Acurácia")
plt.title("Impacto do número de folds no GridSearchCV")
plt.legend()
plt.show()

"""# Treinando o modelo final e avaliando no conjunto de teste"""

floresta = RandomForestClassifier(
    n_estimators = grid.best_params_["n_estimators"],
    max_depth = grid.best_params_["max_depth"],
    min_samples_split = grid.best_params_["min_samples_split"],
    min_samples_leaf = grid.best_params_["min_samples_leaf"],
    criterion = grid.best_params_["criterion"],
    random_state = 123456
)

floresta.fit(X_train_scaled, y_train)

y_pred = floresta.predict(X_test_scaled)

print("Acurácia no teste:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

ConfusionMatrixDisplay.from_predictions(y_test, y_pred)
plt.title("Matriz de confusão - RF")
plt.show()
#

"""# Floresta treinada"""

arvore_vizu = floresta.estimators_[0]

plt.figure(figsize=(16, 8))
plot_tree(
    arvore_vizu,
    feature_names=x.columns,
    class_names=[str(cls) for cls in floresta.classes_],
    filled=True,
    rounded=True,
    fontsize=8,
    max_depth=3,
)
plt.show()

"""# Avaliando importância das variáveis"""

importancia = floresta.feature_importances_
feat_importancia = pd.DataFrame({
    "feature": x.columns,
    "importancia": importancia
}).sort_values(by="importancia", ascending=False)

plt.figure(figsize=(10, 25))
plt.barh(feat_importancia["feature"], feat_importancia["importancia"])
plt.xlabel("Importância")
plt.ylabel("Variável")
plt.title("Importância das variáveis - Random Forest")
plt.gca().invert_yaxis()  # deixa a mais importante no topo
plt.show()

"""# Curva ROC"""

from sklearn.metrics import roc_curve, roc_auc_score, RocCurveDisplay
import matplotlib.pyplot as plt;

y_pred_prob = floresta.predict_proba(X_test_scaled)[:, 1]
fpr_floresta, tpr_floresta, _ = roc_curve(y_test, y_pred_prob)
auc_floresta = roc_auc_score(y_test, y_pred_prob)
plt.figure(figsize=(10, 7))
plt.show()
plt.plot(
    fpr_floresta, tpr_floresta,
    label=f"RF (AUC = {auc_floresta:.3f})"
)
plt.xlabel("FPR")
plt.ylabel("TPR")
plt.title("Curva ROC")
plt.legend()
plt.grid()
plt.show()